# Generated by Django 4.0.4 on 2022-06-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_name', models.CharField(max_length=15)),
                ('adm_fn', models.CharField(max_length=15)),
                ('adm_tel', models.IntegerField()),
                ('adm_login', models.EmailField(max_length=254)),
                ('adm_mdp', models.CharField(max_length=20)),
                ('adm_isadmin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clt_name', models.CharField(max_length=15)),
                ('clt_fn', models.CharField(max_length=15)),
                ('clt_tel', models.CharField(max_length=20)),
                ('clt_login', models.EmailField(max_length=254)),
                ('clt_mdp', models.CharField(max_length=20)),
                ('clt_city', models.CharField(default='casablanca', max_length=25)),
                ('clt_zip', models.CharField(default=20000, max_length=10)),
                ('clt_adresse', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_montant', models.FloatField()),
                ('cmd_datecmd', models.DateField()),
                ('adm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgroubd.administrateur')),
                ('clt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgroubd.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdc_name', models.CharField(max_length=20)),
                ('mdc_price', models.FloatField(default=10.0)),
                ('mdc_dateexp', models.DateField()),
                ('mdc_fournisseur', models.CharField(max_length=15)),
                ('mdc_qts', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_qts', models.IntegerField()),
                ('order_prix', models.FloatField()),
                ('cmd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgroubd.commande')),
                ('mdc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgroubd.medicament')),
            ],
        ),
    ]
